chore: add `natives` so `npm install` succeeds
A clean `npm install` was failing with this error:

```
User@vigatic MINGW64 ~/projects/tulars (elm-0.19)
$ npm i

> elm@0.19.0-bugfix2 install C:\Users\User\projects\tulars\node_modules\elm
> binwrap-install

internal/util/inspect.js:31
const types = internalBinding('types');
              ^

ReferenceError: internalBinding is not defined
    at internal/util/inspect.js:31:15
    at req_ (C:\Users\User\projects\tulars\node_modules\natives\index.js:140:5)
    at require (C:\Users\User\projects\tulars\node_modules\natives\index.js:113:12)
    at util.js:25:21
    at req_ (C:\Users\User\projects\tulars\node_modules\natives\index.js:140:5)
    at require (C:\Users\User\projects\tulars\node_modules\natives\index.js:113:12)
    at fs.js:42:21
    at req_ (C:\Users\User\projects\tulars\node_modules\natives\index.js:140:5)
    at Object.req [as require] (C:\Users\User\projects\tulars\node_modules\natives\index.js:54:10)
    at Object.<anonymous> (C:\Users\User\projects\tulars\node_modules\unzip\node_modules\graceful-fs\fs.js:1:99)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! elm@0.19.0-bugfix2 install: `binwrap-install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the elm@0.19.0-bugfix2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2019-02-03T00_04_22_960Z-debug.log
```